# Generated by Django 4.1.4 on 2023-06-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_conference'),
        ('conference_page', '0002_alter_conferencepage_related_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepage',
            name='related_conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.conference', verbose_name='Related Conference'),
        ),
    ]
