# Generated by Django 4.1.4 on 2023-06-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_page', '0003_alter_conferencepage_related_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_question', models.CharField(max_length=512, verbose_name='Survey Question')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('related_conference_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_page', to='conference_page.conferencepage')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_answer', models.IntegerField(choices=[(1, 'Very few'), (2, 'Fewer'), (3, 'Normal'), (4, 'Pretty'), (5, 'Excessive')], default=3, verbose_name='Survey Answer')),
                ('related_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_survey', to='conference_page.surveyquestion')),
            ],
            options={
                'verbose_name': 'Survey Answer',
                'verbose_name_plural': 'Survey Answers',
                'ordering': ['id'],
            },
        ),
    ]
