# Generated by Django 4.1.4 on 2023-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_page', '0004_surveyquestion_surveyanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencepage',
            name='related_conference',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='related_conference_page',
        ),
        migrations.AddField(
            model_name='conferencepage',
            name='directive_header',
            field=models.CharField(default='Directives', max_length=255, verbose_name='Directives Header'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
    ]
