# Generated by Django 4.1.4 on 2023-06-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_page', '0008_alter_surveyquestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='user',
        ),
    ]
