# Generated by Django 4.1.4 on 2023-06-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_page', '0009_remove_surveyquestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='survey_role',
            field=models.IntegerField(choices=[(0, 'Learner'), (1, 'Tutor')], default=0, verbose_name='Survey Role'),
        ),
    ]
