# Generated by Django 4.1.4 on 2022-12-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='related_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name='Related Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.category', verbose_name='Lesson Category'),
        ),
    ]
