# Generated by Django 4.1.4 on 2023-04-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_content_related_lesson_alter_lesson_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_topic', models.CharField(max_length=255, verbose_name='Conference Topic')),
                ('conference_url', models.URLField(max_length=512, verbose_name='Conference URL')),
                ('related_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name='Related Lesson')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['id'],
            },
        ),
    ]
