# Generated by Django 4.1.4 on 2023-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
